projects:
  maglock:
    schemaPath: app/src/main/graphql/schema.json
    includes:
      - app/src/main/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: ''
        generatedFileName: ''
        docsFilePath: app/src/main/graphql/com/amazonaws/amplify/generated/graphql
        graphQLApiId: 5b4hhglmkzcdjgmlxihn3swh7y
      endpoints:
        prod: >-
          https://bzvqg4tfb5adbpqwa3qsdkciuu.appsync-api.us-east-1.amazonaws.com/graphql
